# Generated by Django 3.1.7 on 2021-08-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='duration of the quiz(min)')),
                ('required_score_to_pass', models.IntegerField(help_text='required score to pass the quiz')),
                ('difficulty', models.CharField(choices=[('very easy', 'very easy'), ('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=9)),
            ],
        ),
    ]
